name: Build

on:
  workflow_call:
    outputs:
      image-tag:
        description: "Image Tag"
        value: ${{ jobs.build.outputs.tag}}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.TAG }}
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Image Tag
        id: tag    
        run: |
          echo "TAG=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        id: build
        run: |
          IMAGE_NAME="${{ secrets.DOCKER_USERNAME }}/my-python-app"
          IMAGE_TAG="${{ steps.tag.outputs.TAG }}"
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "A TAG da Imagem: $IMAGE_TAG"
          echo "Nome da Imagem: $IMAGE_NAME:$IMAGE_TAG"
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG
          echo "A Imagem é: $IMAGE_NAME:$IMAGE_TAG"

