name: Deploy

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Verify Docker Image Input
        run: |
          if [ -z "${{ inputs.docker_image }}" ]; then
            echo "Docker image input is required."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print Image Tag
        run: echo "The Docker image is:" ${{ inputs.docker_image }}

