name: Deploy

on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: robarros
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Print Image Tag
        run: echo "The Docker image is:" ${{ inputs.docker_image }}
